# Generated by Django 5.2.9 on 2025-12-29 15:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="published"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Maximum 150 characters.",
                        max_length=150,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Maximum 200 characters.",
                        max_length=200,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name="weight",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="published"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Maximum 150 characters.",
                        max_length=150,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Maximum 200 characters.",
                        max_length=200,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="published"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Maximum 150 characters.",
                        max_length=150,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="update date"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Select a category for the item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="item",
                        to="catalog.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        help_text="Select tags for the item",
                        related_query_name="item",
                        to="catalog.tag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "default_related_name": "items",
            },
        ),
    ]
