# Generated by Django 5.2.9 on 2026-01-02 11:28

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text=(
                    'The text must contain the words "excellent" or "luxurious".',
                ),
                validators=[
                    catalog.validators.ValidateMustContain("excellent", "luxurious")
                ],
                verbose_name="text",
            ),
        ),
    ]
