# Generated by Django 5.2.9 on 2026-01-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="canonical_name",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Canonical name",
                max_length=150,
                unique=True,
                verbose_name="canonical name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="canonical_name",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Canonical name",
                max_length=150,
                unique=True,
                verbose_name="canonical name",
            ),
            preserve_default=False,
        ),
    ]
